### ISSUE TITLE
Замечание

### ISSUE THREAD

**Issue by gabmars** [Nepruxa/pythonLabs#1]
2 Условие и корректировка индекса работают неправильно + внимательнее читайте задание
3 Внимательнее читайте задание
4 При, как минимум, одном входном числе программа будет работать бесконечно
7 Одно из условий проверки пароля не выполняется
8 Нужно выполнить задание не используя дополнительные модули

**Comment by Nepruxa** [comment]
2 Исправил
3 Исправил 
4 При 0 цикл уходит в небо, поставил предохранитель
7 Не проверялось наличие спец символов. Задолбался прописывать все возможные спец символы для проверки условия, и сгенерировал регулярку, вы вроде говорили что так можно
8 Сделал с использованием extend
